# Generated by Django 2.1.1 on 2018-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/music_album_covers'),
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
