# Generated by Django 2.1.1 on 2019-02-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180902_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='duration_sec',
            field=models.IntegerField(default=65),
            preserve_default=False,
        ),
    ]
