# Generated by Django 2.1.1 on 2019-02-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_musictrack_duration_sec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musictrack',
            old_name='duration_sec',
            new_name='durationSec',
        ),
    ]
