# Generated by Django 2.1.1 on 2019-02-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190217_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrack',
            name='audio',
            field=models.FileField(null=True, upload_to='audio'),
        ),
    ]
